project:
  type: website
  output-dir: output/quarto

website:
  title: "me_dia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: media_report.qmd
        text: Media report
      - href: cross_platform_guide.qmd
        text: User Guide

format:
  html:
    toc: true
    number-sections: false
